[package]
name = "rawhide"
version = "0.6.5"
authors = ["Warren Galyen"]
description = "A library to decode camera raw formats"
#documentation = "..."
#homepage = "..."
repository = "https://github.com/warrengalyen/rawhide"
license = "LGPL-2.1"

build = "data/cameras/join.rs"

[dependencies]
itertools = "0.9.0"
toml = "0.2.0"
crossbeam = "0.2.10"
time = "0.1.35"
enum_primitive = "0.1.0"
num = "0.1.35"
num_cpus = "1.0.0"
lazy_static = "0.2.1"
byteorder = "0.5.3"

[build-dependencies]
glob = "0.2.11"

[profile.release]
panic = "unwind"
#debug-assertions = true