[package]
name = "rawhide"
version = "0.1.0"
authors = ["Warren Galyen"]
build = "data/cameras/join.rs"

[dependencies]
itertools = "0.9.0"
toml = "0.2.0"
glob = "0.2.11"

[build-dependencies]
glob = "0.2.11"