[package]
name = "rawhide"
version = "0.35.2"
authors = ["Warren Galyen"]
description = "A library to decode camera raw formats"
#documentation = "..."
#homepage = "..."
repository = "https://github.com/warrengalyen/rawhide"
license = "LGPL-2.1"
categories = ["multimedia::images"]

build = "data/cameras/join.rs"

[dependencies]
toml = "0.4"
time = "0.1"
enum_primitive = "0.1"
num = "0.2"
lazy_static = "1"
byteorder = "1"
rayon = "1"
itertools = "0.7"
serde = "1"
serde_derive = "1"

[build-dependencies]
glob = "0.2.11"
toml = "0.4.5"
rustc_version = "0.2.3"

[profile.release]
panic = "unwind"

[profile.dev]
panic = "unwind"
opt-level = 3

[[bin]]
name = "benchmark"
doc = false

[[bin]]
name = "identify"
doc = false