[package]
name = "rawhide"
version = "0.1.1"
authors = ["Warren Galyen"]
description = "A library to decode camera raw formats"
#documentation = "..."
#homepage = "..."
repository = "https://github.com/warrengalyen/rawhide"
license = "LGPL-2.1"

build = "data/cameras/join.rs"

[dependencies]
itertools = "0.9.0"
toml = "0.2.0"
glob = "0.2.11"

[build-dependencies]
glob = "0.2.11"