[package]
name = "rawhide"
version = "0.29.0"
authors = ["Warren Galyen"]
description = "A library to decode camera raw formats"
#documentation = "..."
#homepage = "..."
repository = "https://github.com/warrengalyen/rawhide"
license = "LGPL-2.1"
categories = ["multimedia::images"]

build = "data/cameras/join.rs"

[dependencies]
toml = "0.2.1"
time = "0.1.35"
enum_primitive = "0.1.0"
num = "0.1.36"
lazy_static = "0.2.2"
byteorder = "0.5.3"
rayon = "0.6.0"
itertools = "0.5.8"

[build-dependencies]
glob = "0.2.11"
toml = "0.2.1"

[profile.release]
panic = "unwind"

[profile.dev]
panic = "unwind"
opt-level = 3

[[bin]]
name = "main"
doc = false